// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddHotKey():Promise<boolean>;

export function DeleteHotKey(arg1:string):Promise<boolean>;

export function GetAllHotKeys():Promise<Array<backend.HotKey>>;

export function UpdateHotKey(arg1:string,arg2:string,arg3:Array<string>):Promise<boolean>;
