// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHotKey() {
  return window['go']['backend']['App']['AddHotKey']();
}

export function DeleteHotKey(arg1) {
  return window['go']['backend']['App']['DeleteHotKey'](arg1);
}

export function GetAllHotKeys() {
  return window['go']['backend']['App']['GetAllHotKeys']();
}

export function UpdateHotKeys(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['UpdateHotKeys'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateResolution(arg1, arg2, arg3) {
  return window['go']['backend']['App']['UpdateResolution'](arg1, arg2, arg3);
}
